"""empty message

Revision ID: 83c5553649ab
Revises: 
Create Date: 2020-03-09 16:34:57.333720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c5553649ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.Text(collation='utf8_general_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('marital_status', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.Integer(), nullable=False),
    sa.Column('speciality', sa.Integer(), nullable=False),
    sa.Column('yearPractice', sa.Integer(), nullable=False),
    sa.Column('workPlace', sa.Integer(), nullable=False),
    sa.Column('holidays', sa.Integer(), nullable=False),
    sa.Column('workHours', sa.Integer(), nullable=False),
    sa.Column('nightShifts', sa.Integer(), nullable=False),
    sa.Column('offHours', sa.Integer(), nullable=False),
    sa.Column('childern', sa.Integer(), nullable=False),
    sa.Column('advancedPatients', sa.Integer(), nullable=False),
    sa.Column('psychoSocial', sa.Integer(), nullable=False),
    sa.Column('skillsTraining', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(collation='utf8_general_ci'), nullable=False),
    sa.ForeignKeyConstraint(['test_name'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(collation='utf8_general_ci'), nullable=False),
    sa.ForeignKeyConstraint(['test_name'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('instructions')
    op.drop_table('users')
    op.drop_table('tests')
    # ### end Alembic commands ###
